# Generated by Django 4.1.1 on 2022-10-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('collegenm', models.CharField(max_length=122)),
                ('events', models.CharField(max_length=122)),
            ],
        ),
    ]
