# Generated by Django 4.1.1 on 2022-11-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='festdesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fest_name', models.CharField(max_length=50)),
                ('fest_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
