# Generated by Django 4.1.1 on 2022-12-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_festdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50)),
                ('e_desc', models.CharField(max_length=100)),
                ('e_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
