# Generated by Django 4.1.1 on 2022-12-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_festdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spon_name', models.CharField(max_length=50)),
                ('spon_logo', models.ImageField(upload_to=None, verbose_name='test.png')),
            ],
        ),
        migrations.AlterField(
            model_name='festdesc',
            name='fest_desc',
            field=models.TextField(max_length=100),
        ),
    ]
