# Generated by Django 4.1.1 on 2022-12-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='e_frm',
            field=models.URLField(null=True),
        ),
    ]
