# Generated by Django 4.1.1 on 2022-12-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sponsers_alter_festdesc_fest_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='teach_coor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='sponsers',
            name='spon_logo',
        ),
    ]
