# Generated by Django 4.1.1 on 2022-12-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_events_e_frm'),
    ]

    operations = [
        migrations.AddField(
            model_name='festdesc',
            name='fest_bg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
