# Generated by Django 4.1.1 on 2022-12-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_teach_coor_remove_sponsers_spon_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutp_desc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='festdesc',
            name='fest_desc',
            field=models.TextField(max_length=1000),
        ),
    ]
