# Generated by Django 4.1.1 on 2022-12-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutp_alter_festdesc_fest_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach_coor',
            name='teach_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='pics/'),
        ),
    ]
