# Generated by Django 4.1.1 on 2022-12-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_teach_coor_teach_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachcoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_name', models.CharField(max_length=50)),
                ('teach_img', models.FileField(default=None, max_length=250, null=True, upload_to='pics/')),
                ('url', models.URLField(max_length=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='teach_coor',
        ),
    ]
