# Generated by Django 4.1.1 on 2022-12-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_festdesc_fest_bg'),
        ('home', '0008_delete_aboutp_sponsers_spon_logo'),
    ]

    operations = [
    ]
