# Generated by Django 4.1.1 on 2022-12-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20221218_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_email', models.CharField(max_length=50)),
                ('C_mobile', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.RemoveField(
            model_name='festdesc',
            name='fest_bg',
        ),
        migrations.AlterField(
            model_name='sponsers',
            name='spon_logo',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='teachcoor',
            name='teach_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='static/'),
        ),
    ]
