# Generated by Django 4.1.1 on 2022-12-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_events_e_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='e_desc',
            field=models.CharField(max_length=2000),
        ),
    ]
