# Generated by Django 4.1.1 on 2022-12-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_events_e_desc_alter_main_mdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festdesc',
            name='fest_desc',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='festdesc',
            name='fest_name',
            field=models.CharField(max_length=2000),
        ),
    ]
