# Generated by Django 4.1.1 on 2022-12-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_studcoor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studcoor',
            name='s_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='static/'),
        ),
    ]
